// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brpc/policy/baidu_rpc_meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brpc/options.pb.h"
#include "brpc/streaming_rpc_meta.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto;
namespace brpc {
namespace policy {
class RpcMeta;
class RpcMetaDefaultTypeInternal;
extern RpcMetaDefaultTypeInternal _RpcMeta_default_instance_;
class RpcRequestMeta;
class RpcRequestMetaDefaultTypeInternal;
extern RpcRequestMetaDefaultTypeInternal _RpcRequestMeta_default_instance_;
class RpcResponseMeta;
class RpcResponseMetaDefaultTypeInternal;
extern RpcResponseMetaDefaultTypeInternal _RpcResponseMeta_default_instance_;
}  // namespace policy
}  // namespace brpc
PROTOBUF_NAMESPACE_OPEN
template<> ::brpc::policy::RpcMeta* Arena::CreateMaybeMessage<::brpc::policy::RpcMeta>(Arena*);
template<> ::brpc::policy::RpcRequestMeta* Arena::CreateMaybeMessage<::brpc::policy::RpcRequestMeta>(Arena*);
template<> ::brpc::policy::RpcResponseMeta* Arena::CreateMaybeMessage<::brpc::policy::RpcResponseMeta>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace brpc {
namespace policy {

// ===================================================================

class RpcMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.RpcMeta) */ {
 public:
  inline RpcMeta() : RpcMeta(nullptr) {}
  virtual ~RpcMeta();

  RpcMeta(const RpcMeta& from);
  RpcMeta(RpcMeta&& from) noexcept
    : RpcMeta() {
    *this = ::std::move(from);
  }

  inline RpcMeta& operator=(const RpcMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcMeta& operator=(RpcMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RpcMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RpcMeta* internal_default_instance() {
    return reinterpret_cast<const RpcMeta*>(
               &_RpcMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RpcMeta& a, RpcMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RpcMeta* New() const final {
    return CreateMaybeMessage<RpcMeta>(nullptr);
  }

  RpcMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RpcMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RpcMeta& from);
  void MergeFrom(const RpcMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.RpcMeta";
  }
  protected:
  explicit RpcMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAuthenticationDataFieldNumber = 7,
    kRequestFieldNumber = 1,
    kResponseFieldNumber = 2,
    kChunkInfoFieldNumber = 6,
    kStreamSettingsFieldNumber = 8,
    kCorrelationIdFieldNumber = 4,
    kCompressTypeFieldNumber = 3,
    kAttachmentSizeFieldNumber = 5,
  };
  // optional bytes authentication_data = 7;
  bool has_authentication_data() const;
  private:
  bool _internal_has_authentication_data() const;
  public:
  void clear_authentication_data();
  const std::string& authentication_data() const;
  void set_authentication_data(const std::string& value);
  void set_authentication_data(std::string&& value);
  void set_authentication_data(const char* value);
  void set_authentication_data(const void* value, size_t size);
  std::string* mutable_authentication_data();
  std::string* release_authentication_data();
  void set_allocated_authentication_data(std::string* authentication_data);
  private:
  const std::string& _internal_authentication_data() const;
  void _internal_set_authentication_data(const std::string& value);
  std::string* _internal_mutable_authentication_data();
  public:

  // optional .brpc.policy.RpcRequestMeta request = 1;
  bool has_request() const;
  private:
  bool _internal_has_request() const;
  public:
  void clear_request();
  const ::brpc::policy::RpcRequestMeta& request() const;
  ::brpc::policy::RpcRequestMeta* release_request();
  ::brpc::policy::RpcRequestMeta* mutable_request();
  void set_allocated_request(::brpc::policy::RpcRequestMeta* request);
  private:
  const ::brpc::policy::RpcRequestMeta& _internal_request() const;
  ::brpc::policy::RpcRequestMeta* _internal_mutable_request();
  public:
  void unsafe_arena_set_allocated_request(
      ::brpc::policy::RpcRequestMeta* request);
  ::brpc::policy::RpcRequestMeta* unsafe_arena_release_request();

  // optional .brpc.policy.RpcResponseMeta response = 2;
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  const ::brpc::policy::RpcResponseMeta& response() const;
  ::brpc::policy::RpcResponseMeta* release_response();
  ::brpc::policy::RpcResponseMeta* mutable_response();
  void set_allocated_response(::brpc::policy::RpcResponseMeta* response);
  private:
  const ::brpc::policy::RpcResponseMeta& _internal_response() const;
  ::brpc::policy::RpcResponseMeta* _internal_mutable_response();
  public:
  void unsafe_arena_set_allocated_response(
      ::brpc::policy::RpcResponseMeta* response);
  ::brpc::policy::RpcResponseMeta* unsafe_arena_release_response();

  // optional .brpc.ChunkInfo chunk_info = 6;
  bool has_chunk_info() const;
  private:
  bool _internal_has_chunk_info() const;
  public:
  void clear_chunk_info();
  const ::brpc::ChunkInfo& chunk_info() const;
  ::brpc::ChunkInfo* release_chunk_info();
  ::brpc::ChunkInfo* mutable_chunk_info();
  void set_allocated_chunk_info(::brpc::ChunkInfo* chunk_info);
  private:
  const ::brpc::ChunkInfo& _internal_chunk_info() const;
  ::brpc::ChunkInfo* _internal_mutable_chunk_info();
  public:
  void unsafe_arena_set_allocated_chunk_info(
      ::brpc::ChunkInfo* chunk_info);
  ::brpc::ChunkInfo* unsafe_arena_release_chunk_info();

  // optional .brpc.StreamSettings stream_settings = 8;
  bool has_stream_settings() const;
  private:
  bool _internal_has_stream_settings() const;
  public:
  void clear_stream_settings();
  const ::brpc::StreamSettings& stream_settings() const;
  ::brpc::StreamSettings* release_stream_settings();
  ::brpc::StreamSettings* mutable_stream_settings();
  void set_allocated_stream_settings(::brpc::StreamSettings* stream_settings);
  private:
  const ::brpc::StreamSettings& _internal_stream_settings() const;
  ::brpc::StreamSettings* _internal_mutable_stream_settings();
  public:
  void unsafe_arena_set_allocated_stream_settings(
      ::brpc::StreamSettings* stream_settings);
  ::brpc::StreamSettings* unsafe_arena_release_stream_settings();

  // optional int64 correlation_id = 4;
  bool has_correlation_id() const;
  private:
  bool _internal_has_correlation_id() const;
  public:
  void clear_correlation_id();
  ::PROTOBUF_NAMESPACE_ID::int64 correlation_id() const;
  void set_correlation_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_correlation_id() const;
  void _internal_set_correlation_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int32 compress_type = 3;
  bool has_compress_type() const;
  private:
  bool _internal_has_compress_type() const;
  public:
  void clear_compress_type();
  ::PROTOBUF_NAMESPACE_ID::int32 compress_type() const;
  void set_compress_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_compress_type() const;
  void _internal_set_compress_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 attachment_size = 5;
  bool has_attachment_size() const;
  private:
  bool _internal_has_attachment_size() const;
  public:
  void clear_attachment_size();
  ::PROTOBUF_NAMESPACE_ID::int32 attachment_size() const;
  void set_attachment_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_attachment_size() const;
  void _internal_set_attachment_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:brpc.policy.RpcMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr authentication_data_;
  ::brpc::policy::RpcRequestMeta* request_;
  ::brpc::policy::RpcResponseMeta* response_;
  ::brpc::ChunkInfo* chunk_info_;
  ::brpc::StreamSettings* stream_settings_;
  ::PROTOBUF_NAMESPACE_ID::int64 correlation_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 compress_type_;
  ::PROTOBUF_NAMESPACE_ID::int32 attachment_size_;
  friend struct ::TableStruct_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto;
};
// -------------------------------------------------------------------

class RpcRequestMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.RpcRequestMeta) */ {
 public:
  inline RpcRequestMeta() : RpcRequestMeta(nullptr) {}
  virtual ~RpcRequestMeta();

  RpcRequestMeta(const RpcRequestMeta& from);
  RpcRequestMeta(RpcRequestMeta&& from) noexcept
    : RpcRequestMeta() {
    *this = ::std::move(from);
  }

  inline RpcRequestMeta& operator=(const RpcRequestMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcRequestMeta& operator=(RpcRequestMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RpcRequestMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RpcRequestMeta* internal_default_instance() {
    return reinterpret_cast<const RpcRequestMeta*>(
               &_RpcRequestMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RpcRequestMeta& a, RpcRequestMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcRequestMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcRequestMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RpcRequestMeta* New() const final {
    return CreateMaybeMessage<RpcRequestMeta>(nullptr);
  }

  RpcRequestMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RpcRequestMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RpcRequestMeta& from);
  void MergeFrom(const RpcRequestMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcRequestMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.RpcRequestMeta";
  }
  protected:
  explicit RpcRequestMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kMethodNameFieldNumber = 2,
    kLogIdFieldNumber = 3,
    kTraceIdFieldNumber = 4,
    kSpanIdFieldNumber = 5,
    kParentSpanIdFieldNumber = 6,
  };
  // required string service_name = 1;
  bool has_service_name() const;
  private:
  bool _internal_has_service_name() const;
  public:
  void clear_service_name();
  const std::string& service_name() const;
  void set_service_name(const std::string& value);
  void set_service_name(std::string&& value);
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  std::string* mutable_service_name();
  std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // required string method_name = 2;
  bool has_method_name() const;
  private:
  bool _internal_has_method_name() const;
  public:
  void clear_method_name();
  const std::string& method_name() const;
  void set_method_name(const std::string& value);
  void set_method_name(std::string&& value);
  void set_method_name(const char* value);
  void set_method_name(const char* value, size_t size);
  std::string* mutable_method_name();
  std::string* release_method_name();
  void set_allocated_method_name(std::string* method_name);
  private:
  const std::string& _internal_method_name() const;
  void _internal_set_method_name(const std::string& value);
  std::string* _internal_mutable_method_name();
  public:

  // optional int64 log_id = 3;
  bool has_log_id() const;
  private:
  bool _internal_has_log_id() const;
  public:
  void clear_log_id();
  ::PROTOBUF_NAMESPACE_ID::int64 log_id() const;
  void set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_log_id() const;
  void _internal_set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 trace_id = 4;
  bool has_trace_id() const;
  private:
  bool _internal_has_trace_id() const;
  public:
  void clear_trace_id();
  ::PROTOBUF_NAMESPACE_ID::int64 trace_id() const;
  void set_trace_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_trace_id() const;
  void _internal_set_trace_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 span_id = 5;
  bool has_span_id() const;
  private:
  bool _internal_has_span_id() const;
  public:
  void clear_span_id();
  ::PROTOBUF_NAMESPACE_ID::int64 span_id() const;
  void set_span_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_span_id() const;
  void _internal_set_span_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 parent_span_id = 6;
  bool has_parent_span_id() const;
  private:
  bool _internal_has_parent_span_id() const;
  public:
  void clear_parent_span_id();
  ::PROTOBUF_NAMESPACE_ID::int64 parent_span_id() const;
  void set_parent_span_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_parent_span_id() const;
  void _internal_set_parent_span_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:brpc.policy.RpcRequestMeta)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name_;
  ::PROTOBUF_NAMESPACE_ID::int64 log_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 trace_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 span_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 parent_span_id_;
  friend struct ::TableStruct_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto;
};
// -------------------------------------------------------------------

class RpcResponseMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.RpcResponseMeta) */ {
 public:
  inline RpcResponseMeta() : RpcResponseMeta(nullptr) {}
  virtual ~RpcResponseMeta();

  RpcResponseMeta(const RpcResponseMeta& from);
  RpcResponseMeta(RpcResponseMeta&& from) noexcept
    : RpcResponseMeta() {
    *this = ::std::move(from);
  }

  inline RpcResponseMeta& operator=(const RpcResponseMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcResponseMeta& operator=(RpcResponseMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RpcResponseMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RpcResponseMeta* internal_default_instance() {
    return reinterpret_cast<const RpcResponseMeta*>(
               &_RpcResponseMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RpcResponseMeta& a, RpcResponseMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcResponseMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcResponseMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RpcResponseMeta* New() const final {
    return CreateMaybeMessage<RpcResponseMeta>(nullptr);
  }

  RpcResponseMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RpcResponseMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RpcResponseMeta& from);
  void MergeFrom(const RpcResponseMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcResponseMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.RpcResponseMeta";
  }
  protected:
  explicit RpcResponseMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorTextFieldNumber = 2,
    kErrorCodeFieldNumber = 1,
  };
  // optional string error_text = 2;
  bool has_error_text() const;
  private:
  bool _internal_has_error_text() const;
  public:
  void clear_error_text();
  const std::string& error_text() const;
  void set_error_text(const std::string& value);
  void set_error_text(std::string&& value);
  void set_error_text(const char* value);
  void set_error_text(const char* value, size_t size);
  std::string* mutable_error_text();
  std::string* release_error_text();
  void set_allocated_error_text(std::string* error_text);
  private:
  const std::string& _internal_error_text() const;
  void _internal_set_error_text(const std::string& value);
  std::string* _internal_mutable_error_text();
  public:

  // optional int32 error_code = 1;
  bool has_error_code() const;
  private:
  bool _internal_has_error_code() const;
  public:
  void clear_error_code();
  ::PROTOBUF_NAMESPACE_ID::int32 error_code() const;
  void set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_error_code() const;
  void _internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:brpc.policy.RpcResponseMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_text_;
  ::PROTOBUF_NAMESPACE_ID::int32 error_code_;
  friend struct ::TableStruct_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RpcMeta

// optional .brpc.policy.RpcRequestMeta request = 1;
inline bool RpcMeta::_internal_has_request() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || request_ != nullptr);
  return value;
}
inline bool RpcMeta::has_request() const {
  return _internal_has_request();
}
inline void RpcMeta::clear_request() {
  if (request_ != nullptr) request_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::brpc::policy::RpcRequestMeta& RpcMeta::_internal_request() const {
  const ::brpc::policy::RpcRequestMeta* p = request_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::policy::RpcRequestMeta*>(
      &::brpc::policy::_RpcRequestMeta_default_instance_);
}
inline const ::brpc::policy::RpcRequestMeta& RpcMeta::request() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.request)
  return _internal_request();
}
inline void RpcMeta::unsafe_arena_set_allocated_request(
    ::brpc::policy::RpcRequestMeta* request) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_);
  }
  request_ = request;
  if (request) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.RpcMeta.request)
}
inline ::brpc::policy::RpcRequestMeta* RpcMeta::release_request() {
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::RpcRequestMeta* temp = request_;
  request_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::policy::RpcRequestMeta* RpcMeta::unsafe_arena_release_request() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcMeta.request)
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::RpcRequestMeta* temp = request_;
  request_ = nullptr;
  return temp;
}
inline ::brpc::policy::RpcRequestMeta* RpcMeta::_internal_mutable_request() {
  _has_bits_[0] |= 0x00000002u;
  if (request_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::policy::RpcRequestMeta>(GetArena());
    request_ = p;
  }
  return request_;
}
inline ::brpc::policy::RpcRequestMeta* RpcMeta::mutable_request() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcMeta.request)
  return _internal_mutable_request();
}
inline void RpcMeta::set_allocated_request(::brpc::policy::RpcRequestMeta* request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete request_;
  }
  if (request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(request);
    if (message_arena != submessage_arena) {
      request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  request_ = request;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcMeta.request)
}

// optional .brpc.policy.RpcResponseMeta response = 2;
inline bool RpcMeta::_internal_has_response() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || response_ != nullptr);
  return value;
}
inline bool RpcMeta::has_response() const {
  return _internal_has_response();
}
inline void RpcMeta::clear_response() {
  if (response_ != nullptr) response_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::brpc::policy::RpcResponseMeta& RpcMeta::_internal_response() const {
  const ::brpc::policy::RpcResponseMeta* p = response_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::policy::RpcResponseMeta*>(
      &::brpc::policy::_RpcResponseMeta_default_instance_);
}
inline const ::brpc::policy::RpcResponseMeta& RpcMeta::response() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.response)
  return _internal_response();
}
inline void RpcMeta::unsafe_arena_set_allocated_response(
    ::brpc::policy::RpcResponseMeta* response) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_);
  }
  response_ = response;
  if (response) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.RpcMeta.response)
}
inline ::brpc::policy::RpcResponseMeta* RpcMeta::release_response() {
  _has_bits_[0] &= ~0x00000004u;
  ::brpc::policy::RpcResponseMeta* temp = response_;
  response_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::policy::RpcResponseMeta* RpcMeta::unsafe_arena_release_response() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcMeta.response)
  _has_bits_[0] &= ~0x00000004u;
  ::brpc::policy::RpcResponseMeta* temp = response_;
  response_ = nullptr;
  return temp;
}
inline ::brpc::policy::RpcResponseMeta* RpcMeta::_internal_mutable_response() {
  _has_bits_[0] |= 0x00000004u;
  if (response_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::policy::RpcResponseMeta>(GetArena());
    response_ = p;
  }
  return response_;
}
inline ::brpc::policy::RpcResponseMeta* RpcMeta::mutable_response() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcMeta.response)
  return _internal_mutable_response();
}
inline void RpcMeta::set_allocated_response(::brpc::policy::RpcResponseMeta* response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete response_;
  }
  if (response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(response);
    if (message_arena != submessage_arena) {
      response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  response_ = response;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcMeta.response)
}

// optional int32 compress_type = 3;
inline bool RpcMeta::_internal_has_compress_type() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool RpcMeta::has_compress_type() const {
  return _internal_has_compress_type();
}
inline void RpcMeta::clear_compress_type() {
  compress_type_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcMeta::_internal_compress_type() const {
  return compress_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcMeta::compress_type() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.compress_type)
  return _internal_compress_type();
}
inline void RpcMeta::_internal_set_compress_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  compress_type_ = value;
}
inline void RpcMeta::set_compress_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_compress_type(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcMeta.compress_type)
}

// optional int64 correlation_id = 4;
inline bool RpcMeta::_internal_has_correlation_id() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool RpcMeta::has_correlation_id() const {
  return _internal_has_correlation_id();
}
inline void RpcMeta::clear_correlation_id() {
  correlation_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcMeta::_internal_correlation_id() const {
  return correlation_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcMeta::correlation_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.correlation_id)
  return _internal_correlation_id();
}
inline void RpcMeta::_internal_set_correlation_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  correlation_id_ = value;
}
inline void RpcMeta::set_correlation_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_correlation_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcMeta.correlation_id)
}

// optional int32 attachment_size = 5;
inline bool RpcMeta::_internal_has_attachment_size() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool RpcMeta::has_attachment_size() const {
  return _internal_has_attachment_size();
}
inline void RpcMeta::clear_attachment_size() {
  attachment_size_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcMeta::_internal_attachment_size() const {
  return attachment_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcMeta::attachment_size() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.attachment_size)
  return _internal_attachment_size();
}
inline void RpcMeta::_internal_set_attachment_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000080u;
  attachment_size_ = value;
}
inline void RpcMeta::set_attachment_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_attachment_size(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcMeta.attachment_size)
}

// optional .brpc.ChunkInfo chunk_info = 6;
inline bool RpcMeta::_internal_has_chunk_info() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || chunk_info_ != nullptr);
  return value;
}
inline bool RpcMeta::has_chunk_info() const {
  return _internal_has_chunk_info();
}
inline const ::brpc::ChunkInfo& RpcMeta::_internal_chunk_info() const {
  const ::brpc::ChunkInfo* p = chunk_info_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::ChunkInfo*>(
      &::brpc::_ChunkInfo_default_instance_);
}
inline const ::brpc::ChunkInfo& RpcMeta::chunk_info() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.chunk_info)
  return _internal_chunk_info();
}
inline void RpcMeta::unsafe_arena_set_allocated_chunk_info(
    ::brpc::ChunkInfo* chunk_info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(chunk_info_);
  }
  chunk_info_ = chunk_info;
  if (chunk_info) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.RpcMeta.chunk_info)
}
inline ::brpc::ChunkInfo* RpcMeta::release_chunk_info() {
  _has_bits_[0] &= ~0x00000008u;
  ::brpc::ChunkInfo* temp = chunk_info_;
  chunk_info_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::ChunkInfo* RpcMeta::unsafe_arena_release_chunk_info() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcMeta.chunk_info)
  _has_bits_[0] &= ~0x00000008u;
  ::brpc::ChunkInfo* temp = chunk_info_;
  chunk_info_ = nullptr;
  return temp;
}
inline ::brpc::ChunkInfo* RpcMeta::_internal_mutable_chunk_info() {
  _has_bits_[0] |= 0x00000008u;
  if (chunk_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::ChunkInfo>(GetArena());
    chunk_info_ = p;
  }
  return chunk_info_;
}
inline ::brpc::ChunkInfo* RpcMeta::mutable_chunk_info() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcMeta.chunk_info)
  return _internal_mutable_chunk_info();
}
inline void RpcMeta::set_allocated_chunk_info(::brpc::ChunkInfo* chunk_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(chunk_info_);
  }
  if (chunk_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(chunk_info)->GetArena();
    if (message_arena != submessage_arena) {
      chunk_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, chunk_info, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  chunk_info_ = chunk_info;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcMeta.chunk_info)
}

// optional bytes authentication_data = 7;
inline bool RpcMeta::_internal_has_authentication_data() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RpcMeta::has_authentication_data() const {
  return _internal_has_authentication_data();
}
inline void RpcMeta::clear_authentication_data() {
  authentication_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RpcMeta::authentication_data() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.authentication_data)
  return _internal_authentication_data();
}
inline void RpcMeta::set_authentication_data(const std::string& value) {
  _internal_set_authentication_data(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcMeta.authentication_data)
}
inline std::string* RpcMeta::mutable_authentication_data() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcMeta.authentication_data)
  return _internal_mutable_authentication_data();
}
inline const std::string& RpcMeta::_internal_authentication_data() const {
  return authentication_data_.Get();
}
inline void RpcMeta::_internal_set_authentication_data(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  authentication_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RpcMeta::set_authentication_data(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  authentication_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.RpcMeta.authentication_data)
}
inline void RpcMeta::set_authentication_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  authentication_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.RpcMeta.authentication_data)
}
inline void RpcMeta::set_authentication_data(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  authentication_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.RpcMeta.authentication_data)
}
inline std::string* RpcMeta::_internal_mutable_authentication_data() {
  _has_bits_[0] |= 0x00000001u;
  return authentication_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RpcMeta::release_authentication_data() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcMeta.authentication_data)
  if (!_internal_has_authentication_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return authentication_data_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RpcMeta::set_allocated_authentication_data(std::string* authentication_data) {
  if (authentication_data != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  authentication_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), authentication_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcMeta.authentication_data)
}

// optional .brpc.StreamSettings stream_settings = 8;
inline bool RpcMeta::_internal_has_stream_settings() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || stream_settings_ != nullptr);
  return value;
}
inline bool RpcMeta::has_stream_settings() const {
  return _internal_has_stream_settings();
}
inline const ::brpc::StreamSettings& RpcMeta::_internal_stream_settings() const {
  const ::brpc::StreamSettings* p = stream_settings_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::StreamSettings*>(
      &::brpc::_StreamSettings_default_instance_);
}
inline const ::brpc::StreamSettings& RpcMeta::stream_settings() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcMeta.stream_settings)
  return _internal_stream_settings();
}
inline void RpcMeta::unsafe_arena_set_allocated_stream_settings(
    ::brpc::StreamSettings* stream_settings) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stream_settings_);
  }
  stream_settings_ = stream_settings;
  if (stream_settings) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.RpcMeta.stream_settings)
}
inline ::brpc::StreamSettings* RpcMeta::release_stream_settings() {
  _has_bits_[0] &= ~0x00000010u;
  ::brpc::StreamSettings* temp = stream_settings_;
  stream_settings_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::StreamSettings* RpcMeta::unsafe_arena_release_stream_settings() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcMeta.stream_settings)
  _has_bits_[0] &= ~0x00000010u;
  ::brpc::StreamSettings* temp = stream_settings_;
  stream_settings_ = nullptr;
  return temp;
}
inline ::brpc::StreamSettings* RpcMeta::_internal_mutable_stream_settings() {
  _has_bits_[0] |= 0x00000010u;
  if (stream_settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::StreamSettings>(GetArena());
    stream_settings_ = p;
  }
  return stream_settings_;
}
inline ::brpc::StreamSettings* RpcMeta::mutable_stream_settings() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcMeta.stream_settings)
  return _internal_mutable_stream_settings();
}
inline void RpcMeta::set_allocated_stream_settings(::brpc::StreamSettings* stream_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(stream_settings_);
  }
  if (stream_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stream_settings)->GetArena();
    if (message_arena != submessage_arena) {
      stream_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stream_settings, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  stream_settings_ = stream_settings;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcMeta.stream_settings)
}

// -------------------------------------------------------------------

// RpcRequestMeta

// required string service_name = 1;
inline bool RpcRequestMeta::_internal_has_service_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_service_name() const {
  return _internal_has_service_name();
}
inline void RpcRequestMeta::clear_service_name() {
  service_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RpcRequestMeta::service_name() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.service_name)
  return _internal_service_name();
}
inline void RpcRequestMeta::set_service_name(const std::string& value) {
  _internal_set_service_name(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.service_name)
}
inline std::string* RpcRequestMeta::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcRequestMeta.service_name)
  return _internal_mutable_service_name();
}
inline const std::string& RpcRequestMeta::_internal_service_name() const {
  return service_name_.Get();
}
inline void RpcRequestMeta::_internal_set_service_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RpcRequestMeta::set_service_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  service_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.RpcRequestMeta.service_name)
}
inline void RpcRequestMeta::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.RpcRequestMeta.service_name)
}
inline void RpcRequestMeta::set_service_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  service_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.RpcRequestMeta.service_name)
}
inline std::string* RpcRequestMeta::_internal_mutable_service_name() {
  _has_bits_[0] |= 0x00000001u;
  return service_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RpcRequestMeta::release_service_name() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcRequestMeta.service_name)
  if (!_internal_has_service_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return service_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RpcRequestMeta::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  service_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcRequestMeta.service_name)
}

// required string method_name = 2;
inline bool RpcRequestMeta::_internal_has_method_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_method_name() const {
  return _internal_has_method_name();
}
inline void RpcRequestMeta::clear_method_name() {
  method_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RpcRequestMeta::method_name() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.method_name)
  return _internal_method_name();
}
inline void RpcRequestMeta::set_method_name(const std::string& value) {
  _internal_set_method_name(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.method_name)
}
inline std::string* RpcRequestMeta::mutable_method_name() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcRequestMeta.method_name)
  return _internal_mutable_method_name();
}
inline const std::string& RpcRequestMeta::_internal_method_name() const {
  return method_name_.Get();
}
inline void RpcRequestMeta::_internal_set_method_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  method_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RpcRequestMeta::set_method_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  method_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.RpcRequestMeta.method_name)
}
inline void RpcRequestMeta::set_method_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  method_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.RpcRequestMeta.method_name)
}
inline void RpcRequestMeta::set_method_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  method_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.RpcRequestMeta.method_name)
}
inline std::string* RpcRequestMeta::_internal_mutable_method_name() {
  _has_bits_[0] |= 0x00000002u;
  return method_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RpcRequestMeta::release_method_name() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcRequestMeta.method_name)
  if (!_internal_has_method_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return method_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RpcRequestMeta::set_allocated_method_name(std::string* method_name) {
  if (method_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  method_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), method_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcRequestMeta.method_name)
}

// optional int64 log_id = 3;
inline bool RpcRequestMeta::_internal_has_log_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_log_id() const {
  return _internal_has_log_id();
}
inline void RpcRequestMeta::clear_log_id() {
  log_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::_internal_log_id() const {
  return log_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::log_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.log_id)
  return _internal_log_id();
}
inline void RpcRequestMeta::_internal_set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  log_id_ = value;
}
inline void RpcRequestMeta::set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_log_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.log_id)
}

// optional int64 trace_id = 4;
inline bool RpcRequestMeta::_internal_has_trace_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_trace_id() const {
  return _internal_has_trace_id();
}
inline void RpcRequestMeta::clear_trace_id() {
  trace_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::_internal_trace_id() const {
  return trace_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::trace_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.trace_id)
  return _internal_trace_id();
}
inline void RpcRequestMeta::_internal_set_trace_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000008u;
  trace_id_ = value;
}
inline void RpcRequestMeta::set_trace_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_trace_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.trace_id)
}

// optional int64 span_id = 5;
inline bool RpcRequestMeta::_internal_has_span_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_span_id() const {
  return _internal_has_span_id();
}
inline void RpcRequestMeta::clear_span_id() {
  span_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::_internal_span_id() const {
  return span_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::span_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.span_id)
  return _internal_span_id();
}
inline void RpcRequestMeta::_internal_set_span_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  span_id_ = value;
}
inline void RpcRequestMeta::set_span_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_span_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.span_id)
}

// optional int64 parent_span_id = 6;
inline bool RpcRequestMeta::_internal_has_parent_span_id() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool RpcRequestMeta::has_parent_span_id() const {
  return _internal_has_parent_span_id();
}
inline void RpcRequestMeta::clear_parent_span_id() {
  parent_span_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::_internal_parent_span_id() const {
  return parent_span_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RpcRequestMeta::parent_span_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcRequestMeta.parent_span_id)
  return _internal_parent_span_id();
}
inline void RpcRequestMeta::_internal_set_parent_span_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  parent_span_id_ = value;
}
inline void RpcRequestMeta::set_parent_span_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_parent_span_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcRequestMeta.parent_span_id)
}

// -------------------------------------------------------------------

// RpcResponseMeta

// optional int32 error_code = 1;
inline bool RpcResponseMeta::_internal_has_error_code() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RpcResponseMeta::has_error_code() const {
  return _internal_has_error_code();
}
inline void RpcResponseMeta::clear_error_code() {
  error_code_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcResponseMeta::_internal_error_code() const {
  return error_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcResponseMeta::error_code() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcResponseMeta.error_code)
  return _internal_error_code();
}
inline void RpcResponseMeta::_internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  error_code_ = value;
}
inline void RpcResponseMeta::set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcResponseMeta.error_code)
}

// optional string error_text = 2;
inline bool RpcResponseMeta::_internal_has_error_text() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RpcResponseMeta::has_error_text() const {
  return _internal_has_error_text();
}
inline void RpcResponseMeta::clear_error_text() {
  error_text_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RpcResponseMeta::error_text() const {
  // @@protoc_insertion_point(field_get:brpc.policy.RpcResponseMeta.error_text)
  return _internal_error_text();
}
inline void RpcResponseMeta::set_error_text(const std::string& value) {
  _internal_set_error_text(value);
  // @@protoc_insertion_point(field_set:brpc.policy.RpcResponseMeta.error_text)
}
inline std::string* RpcResponseMeta::mutable_error_text() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.RpcResponseMeta.error_text)
  return _internal_mutable_error_text();
}
inline const std::string& RpcResponseMeta::_internal_error_text() const {
  return error_text_.Get();
}
inline void RpcResponseMeta::_internal_set_error_text(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  error_text_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RpcResponseMeta::set_error_text(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  error_text_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.RpcResponseMeta.error_text)
}
inline void RpcResponseMeta::set_error_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  error_text_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.RpcResponseMeta.error_text)
}
inline void RpcResponseMeta::set_error_text(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  error_text_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.RpcResponseMeta.error_text)
}
inline std::string* RpcResponseMeta::_internal_mutable_error_text() {
  _has_bits_[0] |= 0x00000001u;
  return error_text_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RpcResponseMeta::release_error_text() {
  // @@protoc_insertion_point(field_release:brpc.policy.RpcResponseMeta.error_text)
  if (!_internal_has_error_text()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return error_text_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RpcResponseMeta::set_allocated_error_text(std::string* error_text) {
  if (error_text != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_text,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.RpcResponseMeta.error_text)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace policy
}  // namespace brpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fbaidu_5frpc_5fmeta_2eproto
