// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brpc/policy/mongo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fmongo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fmongo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "brpc/options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_brpc_2fpolicy_2fmongo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_brpc_2fpolicy_2fmongo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_brpc_2fpolicy_2fmongo_2eproto;
namespace brpc {
namespace policy {
class MongoHeader;
class MongoHeaderDefaultTypeInternal;
extern MongoHeaderDefaultTypeInternal _MongoHeader_default_instance_;
class MongoRequest;
class MongoRequestDefaultTypeInternal;
extern MongoRequestDefaultTypeInternal _MongoRequest_default_instance_;
class MongoResponse;
class MongoResponseDefaultTypeInternal;
extern MongoResponseDefaultTypeInternal _MongoResponse_default_instance_;
}  // namespace policy
}  // namespace brpc
PROTOBUF_NAMESPACE_OPEN
template<> ::brpc::policy::MongoHeader* Arena::CreateMaybeMessage<::brpc::policy::MongoHeader>(Arena*);
template<> ::brpc::policy::MongoRequest* Arena::CreateMaybeMessage<::brpc::policy::MongoRequest>(Arena*);
template<> ::brpc::policy::MongoResponse* Arena::CreateMaybeMessage<::brpc::policy::MongoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace brpc {
namespace policy {

enum MongoOp : int {
  OPREPLY = 1,
  DBMSG = 1000,
  DB_UPDATE = 2001,
  DB_INSERT = 2002,
  DB_QUERY = 2004,
  DB_GETMORE = 2005,
  DB_DELETE = 2006,
  DB_KILLCURSORS = 2007,
  DB_COMMAND = 2008,
  DB_COMMANDREPLY = 2009
};
bool MongoOp_IsValid(int value);
constexpr MongoOp MongoOp_MIN = OPREPLY;
constexpr MongoOp MongoOp_MAX = DB_COMMANDREPLY;
constexpr int MongoOp_ARRAYSIZE = MongoOp_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MongoOp_descriptor();
template<typename T>
inline const std::string& MongoOp_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MongoOp>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MongoOp_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MongoOp_descriptor(), enum_t_value);
}
inline bool MongoOp_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MongoOp* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MongoOp>(
    MongoOp_descriptor(), name, value);
}
// ===================================================================

class MongoHeader PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.MongoHeader) */ {
 public:
  inline MongoHeader() : MongoHeader(nullptr) {}
  virtual ~MongoHeader();

  MongoHeader(const MongoHeader& from);
  MongoHeader(MongoHeader&& from) noexcept
    : MongoHeader() {
    *this = ::std::move(from);
  }

  inline MongoHeader& operator=(const MongoHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline MongoHeader& operator=(MongoHeader&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MongoHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MongoHeader* internal_default_instance() {
    return reinterpret_cast<const MongoHeader*>(
               &_MongoHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MongoHeader& a, MongoHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(MongoHeader* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MongoHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MongoHeader* New() const final {
    return CreateMaybeMessage<MongoHeader>(nullptr);
  }

  MongoHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MongoHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MongoHeader& from);
  void MergeFrom(const MongoHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MongoHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.MongoHeader";
  }
  protected:
  explicit MongoHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fmongo_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fmongo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageLengthFieldNumber = 1,
    kRequestIdFieldNumber = 2,
    kResponseToFieldNumber = 3,
    kOpCodeFieldNumber = 4,
  };
  // required int32 message_length = 1;
  bool has_message_length() const;
  private:
  bool _internal_has_message_length() const;
  public:
  void clear_message_length();
  ::PROTOBUF_NAMESPACE_ID::int32 message_length() const;
  void set_message_length(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_message_length() const;
  void _internal_set_message_length(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 request_id = 2;
  bool has_request_id() const;
  private:
  bool _internal_has_request_id() const;
  public:
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::int32 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 response_to = 3;
  bool has_response_to() const;
  private:
  bool _internal_has_response_to() const;
  public:
  void clear_response_to();
  ::PROTOBUF_NAMESPACE_ID::int32 response_to() const;
  void set_response_to(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_response_to() const;
  void _internal_set_response_to(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required .brpc.policy.MongoOp op_code = 4;
  bool has_op_code() const;
  private:
  bool _internal_has_op_code() const;
  public:
  void clear_op_code();
  ::brpc::policy::MongoOp op_code() const;
  void set_op_code(::brpc::policy::MongoOp value);
  private:
  ::brpc::policy::MongoOp _internal_op_code() const;
  void _internal_set_op_code(::brpc::policy::MongoOp value);
  public:

  // @@protoc_insertion_point(class_scope:brpc.policy.MongoHeader)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 message_length_;
  ::PROTOBUF_NAMESPACE_ID::int32 request_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 response_to_;
  int op_code_;
  friend struct ::TableStruct_brpc_2fpolicy_2fmongo_2eproto;
};
// -------------------------------------------------------------------

class MongoRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.MongoRequest) */ {
 public:
  inline MongoRequest() : MongoRequest(nullptr) {}
  virtual ~MongoRequest();

  MongoRequest(const MongoRequest& from);
  MongoRequest(MongoRequest&& from) noexcept
    : MongoRequest() {
    *this = ::std::move(from);
  }

  inline MongoRequest& operator=(const MongoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MongoRequest& operator=(MongoRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MongoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MongoRequest* internal_default_instance() {
    return reinterpret_cast<const MongoRequest*>(
               &_MongoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MongoRequest& a, MongoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MongoRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MongoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MongoRequest* New() const final {
    return CreateMaybeMessage<MongoRequest>(nullptr);
  }

  MongoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MongoRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MongoRequest& from);
  void MergeFrom(const MongoRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MongoRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.MongoRequest";
  }
  protected:
  explicit MongoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fmongo_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fmongo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // required string message = 2;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // required .brpc.policy.MongoHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::brpc::policy::MongoHeader& header() const;
  ::brpc::policy::MongoHeader* release_header();
  ::brpc::policy::MongoHeader* mutable_header();
  void set_allocated_header(::brpc::policy::MongoHeader* header);
  private:
  const ::brpc::policy::MongoHeader& _internal_header() const;
  ::brpc::policy::MongoHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::brpc::policy::MongoHeader* header);
  ::brpc::policy::MongoHeader* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:brpc.policy.MongoRequest)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::brpc::policy::MongoHeader* header_;
  friend struct ::TableStruct_brpc_2fpolicy_2fmongo_2eproto;
};
// -------------------------------------------------------------------

class MongoResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:brpc.policy.MongoResponse) */ {
 public:
  inline MongoResponse() : MongoResponse(nullptr) {}
  virtual ~MongoResponse();

  MongoResponse(const MongoResponse& from);
  MongoResponse(MongoResponse&& from) noexcept
    : MongoResponse() {
    *this = ::std::move(from);
  }

  inline MongoResponse& operator=(const MongoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MongoResponse& operator=(MongoResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MongoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MongoResponse* internal_default_instance() {
    return reinterpret_cast<const MongoResponse*>(
               &_MongoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MongoResponse& a, MongoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MongoResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MongoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MongoResponse* New() const final {
    return CreateMaybeMessage<MongoResponse>(nullptr);
  }

  MongoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MongoResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MongoResponse& from);
  void MergeFrom(const MongoResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MongoResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "brpc.policy.MongoResponse";
  }
  protected:
  explicit MongoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_brpc_2fpolicy_2fmongo_2eproto);
    return ::descriptor_table_brpc_2fpolicy_2fmongo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 6,
    kHeaderFieldNumber = 1,
    kCursorIdFieldNumber = 3,
    kResponseFlagsFieldNumber = 2,
    kStartingFromFieldNumber = 4,
    kNumberReturnedFieldNumber = 5,
  };
  // required string message = 6;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // required .brpc.policy.MongoHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::brpc::policy::MongoHeader& header() const;
  ::brpc::policy::MongoHeader* release_header();
  ::brpc::policy::MongoHeader* mutable_header();
  void set_allocated_header(::brpc::policy::MongoHeader* header);
  private:
  const ::brpc::policy::MongoHeader& _internal_header() const;
  ::brpc::policy::MongoHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::brpc::policy::MongoHeader* header);
  ::brpc::policy::MongoHeader* unsafe_arena_release_header();

  // required int64 cursor_id = 3;
  bool has_cursor_id() const;
  private:
  bool _internal_has_cursor_id() const;
  public:
  void clear_cursor_id();
  ::PROTOBUF_NAMESPACE_ID::int64 cursor_id() const;
  void set_cursor_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_cursor_id() const;
  void _internal_set_cursor_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required int32 response_flags = 2;
  bool has_response_flags() const;
  private:
  bool _internal_has_response_flags() const;
  public:
  void clear_response_flags();
  ::PROTOBUF_NAMESPACE_ID::int32 response_flags() const;
  void set_response_flags(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_response_flags() const;
  void _internal_set_response_flags(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 starting_from = 4;
  bool has_starting_from() const;
  private:
  bool _internal_has_starting_from() const;
  public:
  void clear_starting_from();
  ::PROTOBUF_NAMESPACE_ID::int32 starting_from() const;
  void set_starting_from(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_starting_from() const;
  void _internal_set_starting_from(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 number_returned = 5;
  bool has_number_returned() const;
  private:
  bool _internal_has_number_returned() const;
  public:
  void clear_number_returned();
  ::PROTOBUF_NAMESPACE_ID::int32 number_returned() const;
  void set_number_returned(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_number_returned() const;
  void _internal_set_number_returned(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:brpc.policy.MongoResponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::brpc::policy::MongoHeader* header_;
  ::PROTOBUF_NAMESPACE_ID::int64 cursor_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 response_flags_;
  ::PROTOBUF_NAMESPACE_ID::int32 starting_from_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_returned_;
  friend struct ::TableStruct_brpc_2fpolicy_2fmongo_2eproto;
};
// ===================================================================

class MongoService_Stub;

class MongoService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline MongoService() {};
 public:
  virtual ~MongoService();

  typedef MongoService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void default_method(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::brpc::policy::MongoRequest* request,
                       ::brpc::policy::MongoResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MongoService);
};

class MongoService_Stub : public MongoService {
 public:
  MongoService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  MongoService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~MongoService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements MongoService ------------------------------------------

  void default_method(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::brpc::policy::MongoRequest* request,
                       ::brpc::policy::MongoResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MongoService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MongoHeader

// required int32 message_length = 1;
inline bool MongoHeader::_internal_has_message_length() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MongoHeader::has_message_length() const {
  return _internal_has_message_length();
}
inline void MongoHeader::clear_message_length() {
  message_length_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::_internal_message_length() const {
  return message_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::message_length() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoHeader.message_length)
  return _internal_message_length();
}
inline void MongoHeader::_internal_set_message_length(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  message_length_ = value;
}
inline void MongoHeader::set_message_length(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_message_length(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoHeader.message_length)
}

// required int32 request_id = 2;
inline bool MongoHeader::_internal_has_request_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MongoHeader::has_request_id() const {
  return _internal_has_request_id();
}
inline void MongoHeader::clear_request_id() {
  request_id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::request_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoHeader.request_id)
  return _internal_request_id();
}
inline void MongoHeader::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  request_id_ = value;
}
inline void MongoHeader::set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoHeader.request_id)
}

// required int32 response_to = 3;
inline bool MongoHeader::_internal_has_response_to() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MongoHeader::has_response_to() const {
  return _internal_has_response_to();
}
inline void MongoHeader::clear_response_to() {
  response_to_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::_internal_response_to() const {
  return response_to_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoHeader::response_to() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoHeader.response_to)
  return _internal_response_to();
}
inline void MongoHeader::_internal_set_response_to(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  response_to_ = value;
}
inline void MongoHeader::set_response_to(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_response_to(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoHeader.response_to)
}

// required .brpc.policy.MongoOp op_code = 4;
inline bool MongoHeader::_internal_has_op_code() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool MongoHeader::has_op_code() const {
  return _internal_has_op_code();
}
inline void MongoHeader::clear_op_code() {
  op_code_ = 1;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::brpc::policy::MongoOp MongoHeader::_internal_op_code() const {
  return static_cast< ::brpc::policy::MongoOp >(op_code_);
}
inline ::brpc::policy::MongoOp MongoHeader::op_code() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoHeader.op_code)
  return _internal_op_code();
}
inline void MongoHeader::_internal_set_op_code(::brpc::policy::MongoOp value) {
  assert(::brpc::policy::MongoOp_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  op_code_ = value;
}
inline void MongoHeader::set_op_code(::brpc::policy::MongoOp value) {
  _internal_set_op_code(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoHeader.op_code)
}

// -------------------------------------------------------------------

// MongoRequest

// required .brpc.policy.MongoHeader header = 1;
inline bool MongoRequest::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool MongoRequest::has_header() const {
  return _internal_has_header();
}
inline void MongoRequest::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::brpc::policy::MongoHeader& MongoRequest::_internal_header() const {
  const ::brpc::policy::MongoHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::policy::MongoHeader*>(
      &::brpc::policy::_MongoHeader_default_instance_);
}
inline const ::brpc::policy::MongoHeader& MongoRequest::header() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoRequest.header)
  return _internal_header();
}
inline void MongoRequest::unsafe_arena_set_allocated_header(
    ::brpc::policy::MongoHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.MongoRequest.header)
}
inline ::brpc::policy::MongoHeader* MongoRequest::release_header() {
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::MongoHeader* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::policy::MongoHeader* MongoRequest::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:brpc.policy.MongoRequest.header)
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::MongoHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::brpc::policy::MongoHeader* MongoRequest::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000002u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::policy::MongoHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::brpc::policy::MongoHeader* MongoRequest::mutable_header() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.MongoRequest.header)
  return _internal_mutable_header();
}
inline void MongoRequest::set_allocated_header(::brpc::policy::MongoHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.MongoRequest.header)
}

// required string message = 2;
inline bool MongoRequest::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MongoRequest::has_message() const {
  return _internal_has_message();
}
inline void MongoRequest::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MongoRequest::message() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoRequest.message)
  return _internal_message();
}
inline void MongoRequest::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoRequest.message)
}
inline std::string* MongoRequest::mutable_message() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.MongoRequest.message)
  return _internal_mutable_message();
}
inline const std::string& MongoRequest::_internal_message() const {
  return message_.Get();
}
inline void MongoRequest::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MongoRequest::set_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.MongoRequest.message)
}
inline void MongoRequest::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.MongoRequest.message)
}
inline void MongoRequest::set_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.MongoRequest.message)
}
inline std::string* MongoRequest::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000001u;
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MongoRequest::release_message() {
  // @@protoc_insertion_point(field_release:brpc.policy.MongoRequest.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MongoRequest::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.MongoRequest.message)
}

// -------------------------------------------------------------------

// MongoResponse

// required .brpc.policy.MongoHeader header = 1;
inline bool MongoResponse::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool MongoResponse::has_header() const {
  return _internal_has_header();
}
inline void MongoResponse::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::brpc::policy::MongoHeader& MongoResponse::_internal_header() const {
  const ::brpc::policy::MongoHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::brpc::policy::MongoHeader*>(
      &::brpc::policy::_MongoHeader_default_instance_);
}
inline const ::brpc::policy::MongoHeader& MongoResponse::header() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.header)
  return _internal_header();
}
inline void MongoResponse::unsafe_arena_set_allocated_header(
    ::brpc::policy::MongoHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:brpc.policy.MongoResponse.header)
}
inline ::brpc::policy::MongoHeader* MongoResponse::release_header() {
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::MongoHeader* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::brpc::policy::MongoHeader* MongoResponse::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:brpc.policy.MongoResponse.header)
  _has_bits_[0] &= ~0x00000002u;
  ::brpc::policy::MongoHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::brpc::policy::MongoHeader* MongoResponse::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000002u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::brpc::policy::MongoHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::brpc::policy::MongoHeader* MongoResponse::mutable_header() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.MongoResponse.header)
  return _internal_mutable_header();
}
inline void MongoResponse::set_allocated_header(::brpc::policy::MongoHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.MongoResponse.header)
}

// required int32 response_flags = 2;
inline bool MongoResponse::_internal_has_response_flags() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool MongoResponse::has_response_flags() const {
  return _internal_has_response_flags();
}
inline void MongoResponse::clear_response_flags() {
  response_flags_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::_internal_response_flags() const {
  return response_flags_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::response_flags() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.response_flags)
  return _internal_response_flags();
}
inline void MongoResponse::_internal_set_response_flags(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  response_flags_ = value;
}
inline void MongoResponse::set_response_flags(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_response_flags(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoResponse.response_flags)
}

// required int64 cursor_id = 3;
inline bool MongoResponse::_internal_has_cursor_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MongoResponse::has_cursor_id() const {
  return _internal_has_cursor_id();
}
inline void MongoResponse::clear_cursor_id() {
  cursor_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MongoResponse::_internal_cursor_id() const {
  return cursor_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MongoResponse::cursor_id() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.cursor_id)
  return _internal_cursor_id();
}
inline void MongoResponse::_internal_set_cursor_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  cursor_id_ = value;
}
inline void MongoResponse::set_cursor_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_cursor_id(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoResponse.cursor_id)
}

// required int32 starting_from = 4;
inline bool MongoResponse::_internal_has_starting_from() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool MongoResponse::has_starting_from() const {
  return _internal_has_starting_from();
}
inline void MongoResponse::clear_starting_from() {
  starting_from_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::_internal_starting_from() const {
  return starting_from_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::starting_from() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.starting_from)
  return _internal_starting_from();
}
inline void MongoResponse::_internal_set_starting_from(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  starting_from_ = value;
}
inline void MongoResponse::set_starting_from(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_starting_from(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoResponse.starting_from)
}

// required int32 number_returned = 5;
inline bool MongoResponse::_internal_has_number_returned() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool MongoResponse::has_number_returned() const {
  return _internal_has_number_returned();
}
inline void MongoResponse::clear_number_returned() {
  number_returned_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::_internal_number_returned() const {
  return number_returned_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MongoResponse::number_returned() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.number_returned)
  return _internal_number_returned();
}
inline void MongoResponse::_internal_set_number_returned(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  number_returned_ = value;
}
inline void MongoResponse::set_number_returned(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_number_returned(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoResponse.number_returned)
}

// required string message = 6;
inline bool MongoResponse::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MongoResponse::has_message() const {
  return _internal_has_message();
}
inline void MongoResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MongoResponse::message() const {
  // @@protoc_insertion_point(field_get:brpc.policy.MongoResponse.message)
  return _internal_message();
}
inline void MongoResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:brpc.policy.MongoResponse.message)
}
inline std::string* MongoResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:brpc.policy.MongoResponse.message)
  return _internal_mutable_message();
}
inline const std::string& MongoResponse::_internal_message() const {
  return message_.Get();
}
inline void MongoResponse::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MongoResponse::set_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:brpc.policy.MongoResponse.message)
}
inline void MongoResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:brpc.policy.MongoResponse.message)
}
inline void MongoResponse::set_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:brpc.policy.MongoResponse.message)
}
inline std::string* MongoResponse::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000001u;
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MongoResponse::release_message() {
  // @@protoc_insertion_point(field_release:brpc.policy.MongoResponse.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MongoResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:brpc.policy.MongoResponse.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace policy
}  // namespace brpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::brpc::policy::MongoOp> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::brpc::policy::MongoOp>() {
  return ::brpc::policy::MongoOp_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_brpc_2fpolicy_2fmongo_2eproto
