// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idl_options.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_idl_5foptions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_idl_5foptions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_idl_5foptions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_idl_5foptions_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_idl_5foptions_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

enum ConvertibleIdlType : int {
  IDL_AUTO = 0,
  IDL_INT8 = 1,
  IDL_INT16 = 2,
  IDL_INT32 = 3,
  IDL_INT64 = 4,
  IDL_UINT8 = 5,
  IDL_UINT16 = 6,
  IDL_UINT32 = 7,
  IDL_UINT64 = 8,
  IDL_BOOL = 9,
  IDL_FLOAT = 10,
  IDL_DOUBLE = 11,
  IDL_BINARY = 12,
  IDL_STRING = 13
};
bool ConvertibleIdlType_IsValid(int value);
constexpr ConvertibleIdlType ConvertibleIdlType_MIN = IDL_AUTO;
constexpr ConvertibleIdlType ConvertibleIdlType_MAX = IDL_STRING;
constexpr int ConvertibleIdlType_ARRAYSIZE = ConvertibleIdlType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ConvertibleIdlType_descriptor();
template<typename T>
inline const std::string& ConvertibleIdlType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ConvertibleIdlType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ConvertibleIdlType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ConvertibleIdlType_descriptor(), enum_t_value);
}
inline bool ConvertibleIdlType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ConvertibleIdlType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ConvertibleIdlType>(
    ConvertibleIdlType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kIdlSupportFieldNumber = 91000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  idl_support;
static const int kIdlTypeFieldNumber = 91001;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::ConvertibleIdlType, ::ConvertibleIdlType_IsValid>, 14, false >
  idl_type;
static const int kIdlOnFieldNumber = 91002;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< ::PROTOBUF_NAMESPACE_ID::int32 >, 5, false >
  idl_on;
static const int kIdlNameFieldNumber = 91003;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  idl_name;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ConvertibleIdlType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ConvertibleIdlType>() {
  return ::ConvertibleIdlType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_idl_5foptions_2eproto
